// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using VirtualEvent.Model.Data;
using VirtualEvent.Model.Models;


namespace VirtualEvent.Model.Data.Configurations
{
    public partial class AttendanceAttanchmentsConfiguration : IEntityTypeConfiguration<AttendanceAttanchments>
    {
        public void Configure(EntityTypeBuilder<AttendanceAttanchments> entity)
        {
            entity.Property(e => e.Name)
                .IsRequired()
                .HasColumnType("VARCHAR (50)");

            entity.HasOne(d => d.Attendance)
                .WithMany(p => p.AttendanceAttanchments)
                .HasForeignKey(d => d.AttendanceId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<AttendanceAttanchments> entity);
    }
}
