// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using VirtualEvent.Model.Data;
using VirtualEvent.Model.Models;


namespace VirtualEvent.Model.Data.Configurations
{
    public partial class EventsConfiguration : IEntityTypeConfiguration<Events>
    {
        public void Configure(EntityTypeBuilder<Events> entity)
        {
            entity.HasKey(e => e.EventId);

            entity.Property(e => e.EndDate)
                .IsRequired()
                .HasColumnType("DATE");

            entity.Property(e => e.EndTime)
                .IsRequired()
                .HasColumnType("TIME");

            entity.Property(e => e.OrganizerId)
                .IsRequired()
                .HasColumnType("VARCHAR (50)");

            entity.Property(e => e.StartDate)
                .IsRequired()
                .HasColumnType("DATE");

            entity.Property(e => e.StartTime)
                .IsRequired()
                .HasColumnType("TIME");

            entity.Property(e => e.Title)
                .IsRequired()
                .HasColumnType("VARCHAR (250)");

            entity.Property(e => e.Url).IsRequired();

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Events> entity);
    }
}
