// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using VirtualEvent.Model.Data.Configurations;
using VirtualEvent.Model.Models;

#nullable disable

namespace VirtualEvent.Model.Data
{
    public partial class VirtualeventsDbContext : DbContext
    {
        public VirtualeventsDbContext()
        {
        }

        public VirtualeventsDbContext(DbContextOptions<VirtualeventsDbContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Attendance> Attendance { get; set; }
        public virtual DbSet<AttendanceAttanchments> AttendanceAttanchments { get; set; }
        public virtual DbSet<EventAttachments> EventAttachments { get; set; }
        public virtual DbSet<Events> Events { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.ApplyConfiguration(new Configurations.AttendanceConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.AttendanceAttanchmentsConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.EventAttachmentsConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.EventsConfiguration());

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}
