// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace VirtualEvent.Model.Models
{
    public partial class Attendances
    {
        public Attendances()
        {
            AttendanceAttanchments = new HashSet<AttendanceAttanchments>();
        }

        public long AttendanceId { get; set; }
        public long EventId { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string Notes { get; set; }
        public byte[] AttendanceDate { get; set; }

        public virtual Events Event { get; set; }
        public virtual ICollection<AttendanceAttanchments> AttendanceAttanchments { get; set; }
    }
}