// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace VirtualEvent.Model.Models
{
    public partial class Events
    {
        public Events()
        {
            Attendance = new HashSet<Attendance>();
            EventAttachments = new HashSet<EventAttachments>();
        }

        public long EventId { get; set; }
        public string OrganizerId { get; set; }
        public string Title { get; set; }
        public byte[] StartDate { get; set; }
        public byte[] StartTime { get; set; }
        public byte[] EndDate { get; set; }
        public byte[] EndTime { get; set; }
        public string Url { get; set; }
        public string Notes { get; set; }

        public virtual ICollection<Attendance> Attendance { get; set; }
        public virtual ICollection<EventAttachments> EventAttachments { get; set; }
    }
}